channels:
  - "conda-forge"
dependencies:
  - "python=3.10"
  - "pip<=23.0.1"
  - pip:
    - semantic-kernel
    - openai
    - azureml-inference-server-http
    - azureml-contrib-services
    - azure-search-documents==11.4.0b11
