channels:
  - "conda-forge"
dependencies:
  - "python=3.10"
  - "pip<=23.0.1"
  - pip:
    - langchain<0.0.333
    # generative ai SDK dependencies
    - openai
    - pydantic<2
    - azure-ai-generative[evaluate,index,document_parsing]
    # inference server dependencies
    - azureml-inference-server-http
