channels:
  - "conda-forge"
dependencies:
  - "python=3.10"
  - "pip<=23.0.1"
  - pip:
    # generative ai SDK dependencies
    - openai
    - pydantic<2
    - --extra-index-url=https://azuremlsdktestpypi.azureedge.net/Create-Dev-Index/102333570
    - azure-ai-generative==0.5.0
    - azureml-rag[cognitive_search]==0.1.24.1

    - # langchain dependencies, these should be optional in the future
    - # langchain moved Embeddings from langchain.embeddings.base to langchain.schema.embeddings while azureml-rag is still referencing it.
    - # once azureml-rag is updated to 2.0+, we can remove the langchain reference from this file
    - langchain<0.0.293